### ISSUE TITLE
Can't install from Obsidian community plugins.

### ISSUE THREAD

**Issue by alexeiMikhail** [Darakah/obsidian-comments-plugin#3]
Hey there! Sorry if this isn't the right place for this. I'm trying to install this plugin directly from the Obsidian third party plugins tab, but I'm getting an error that "No appropriate version found." I think because the version on Obsidian and the version on Github don't match? I'd try to manually install, but I haven't been able to find instructions on how to do so.

**Comment by Darakah** [comment]
Hello there, 
Yes, this is the right place. 

So, I just uninstalled and re-installed the plugin and it worked fine for me. 
with respect to versions, as specified in the manifest, it requires at least version `0.10.11` of obsidian. What version do you currently have? This is most likely the reason. ( version shown in the about tab of the obsidian settings)

https://github.com/Darakah/obsidian-comments-plugin/blob/e352bc46256b6851077bcefc8213991ada1a25eb/manifest.json#L5

As for the versions problem, the latest release is `0.1.3` (https://github.com/Darakah/obsidian-comments-plugin/releases/tag/0.1.3) as specified also by the manifest file at:

https://github.com/Darakah/obsidian-comments-plugin/blob/e352bc46256b6851077bcefc8213991ada1a25eb/manifest.json#L4

I believe the confusion is from the `apparent latest release` which say 0.1.2 which is shown there because i corrected the tag of that release after the most recent one. 

**_Manual Installation:_**
 If it was not an obsidian version problem, you can manual install it by following these steps:
1. Download the files by clicking -> Code -> download zip
2. Unzip the folder 
3. Using your terminal do the following:

```sh
cd ./obsidian-comments-plugin-main
npm i
npm run dev
```
It should show a message like 

```
rollup v2.38.5
bundles main.ts → ...
created  in 1.7s

[2021-02-08 23:50:03] waiting for changes...
```

Exit the terminal, delete all files in the folder except the following:
- main.js
- style.css
- manifest.json

Place the folder inside your `./obsidian/plugins` folder then activate it from the plugins tab after refreshing the list.

let me know if this does not work or if you need any further help.

**Comment by alexeiMikhail** [comment]
Yup, Obsidian version was the problem. I hadn't realized that I needed to
update Obsidian manually. Thank you so much for the help!
